//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaksinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPOM
    {
        public int id_bpom { get; set; }
        public string name { get; set; }
        public string division { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string username { get; set; }
    }
}
