//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaksinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasien
    {
        public string no_rek_medis { get; set; }
        public string nik { get; set; }
        public string no_registration { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> isReported { get; set; }
        public Nullable<int> id_rumahsakit { get; set; }
    }
}
