//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaksinService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrackingVaksinEntities : DbContext
    {
        public TrackingVaksinEntities()
            : base("name=TrackingVaksinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<BPOM> BPOM { get; set; }
        public virtual DbSet<BPOM_Log_Kedatangan_Vaksin> BPOM_Log_Kedatangan_Vaksin { get; set; }
        public virtual DbSet<BPOM_Log_Penggunaan_Vaksin> BPOM_Log_Penggunaan_Vaksin { get; set; }
        public virtual DbSet<BPOM_Vaksin> BPOM_Vaksin { get; set; }
        public virtual DbSet<Masyarakat> Masyarakat { get; set; }
        public virtual DbSet<Pasien> Pasien { get; set; }
        public virtual DbSet<Produsen> Produsen { get; set; }
        public virtual DbSet<Produsen_Vaksin> Produsen_Vaksin { get; set; }
        public virtual DbSet<RS_Vaksin> RS_Vaksin { get; set; }
        public virtual DbSet<RumahSakit> RumahSakit { get; set; }
    }
}
